version: "3"
services:
  app:
    build: .
  # image: anasakzaz/openclassroom 
    restart: always
    ports:
      - 5003:5003
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  